### PR TITLE
fix(persist): not hydrating when the stored item doesn't contain a version

### LINKED ISSUE #409: Having trouble getting deserialize to work
Sorry for the noob question, I don't know if there's a better forum for these types of issues

I'm trying to persist my accessToken to localstorage. It works great. But when reloading the page, the deserialize function doesn't seem to hydrate the store state at all.

Here's my store
```
// > auth.ts
const useAuthStore = create<AuthStoreState>(
  devtools(
    persist(
      (set) => ({
        accessToken: '',
        setAccessToken: (accessToken) => set((_state) => ({ accessToken })),
      }),
      {
        name: 'AccessToken',
        serialize: ({ state }) => JSON.stringify(state.accessToken),
        deserialize: (accessToken: string) => JSON.parse(`{ "accessToken": "${accessToken}" }`), 
        // --> logging the JSON.parse statement gives { accessToken: "sometokenvalue" }
      }
    )
  )
);

// > in index.jsx
const { accessToken } = useAuthStore(); // --> <empty string>
```

Any ideas what's going wrong here?

### PR DESCRIPTION
**Pull request by AnatoleLucet**
Closes #409

### CODE REVIEW

**Comment by dai-shi** [comment]
@AnatoleLucet 
wow, so many PRs. I mean, very good.
I do have a favor. Would you please change the PR title, so that I can just copy&paste in the release note?
For closed ones too like #455.

**Review by dai-shi — APPROVED** [review]
I'm not sure if this is ideal or what is ideal, but it should be fine.

**Comment by dai-shi** [comment]
@AnatoleLucet can merge master and resolve conflicts please?

**Comment by dai-shi** [comment]
I hope it's fine. 🤞

**Comment by AnatoleLucet** [comment]
Looks fine :ok_hand: thanks

**Pull request merged**
