### PR TITLE
Extra brackets in typescript example

### PR DESCRIPTION
**Pull request by Faithfinder**
This looks more correct

### CODE REVIEW

**Comment by charkour** [comment]
Hey @Faithfinder,

Thanks for the PR, but the original is actually correct. The `create` function is curried to provide accurate types for the store when using typescript. Here is more [documentation](https://github.com/pmndrs/zustand#typescript-usage) to explain the reason in detail.

**Comment by Faithfinder** [comment]
Ah! Thank you. How about this then? If not, feel free to close :)

**Comment by dai-shi** [comment]
459320c
I don't think it's necessary, as it's too repetitive. But, thanks for the feedback. Better way to educate the syntax would be important. 🤔

**Comment by Faithfinder** [comment]
I missed the extra brackets in the text blurb, because I thought you're trying to draw attention to the generic, and that's why I thought the extra brackets in the example are, well, extra >.>

**Comment by dai-shi** [comment]
Yeah, maybe it should more redirect to "TypeScript guide".

What do you guys think? @chrisk-7777 @sewera @dbritto-dev @charkour

**Comment by dbritto-dev** [comment]
I do not know what you think guys but having two syntax for the same could be confusing for some people. I would go for using the curried version for both, javascript and typescript. Then people does not need to rewrite the code to support typescript.

**Comment by dai-shi** [comment]
We are debating in #1430.

**Pull request closed without merging**
