### PR TITLE
[v4-alpha] use mutable source

### PR DESCRIPTION
**Pull request by dai-shi**
originally from #157

### CODE REVIEW

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/zustand/v/4.0.0-alpha.0

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/zustand/v/4.0.0-alpha.1

**Comment by GunboatDiplomat** [comment]
I apologize if my question is not related to this PR, but I am interested to know if zustand ever plans to support level 3 for concurrent rendering (https://github.com/reactwg/react-18/discussions/70)?

**Comment by dai-shi** [comment]
level 3 would probably require multi-version snapshots, and it's probably impossible to extend zustand/valtio api for it. My hope is jotai api might do, but maybe not because jotai api still allows impure operations on write. Overall, the answer is, we are interested, but we don't know.

**Comment by dai-shi** [comment]
Closing. We'll continue the effort in #550.

**Pull request closed without merging**
