### PR TITLE
[Documentation] Add detail example for "Slice Pattern"

### PR DESCRIPTION
**Pull request by detautama**
Add detailed examples for "Slice Pattern" and "Slice Pattern" with "Middlewares"

Check here to view changed documentation
https://github.com/pmndrs/zustand/blob/1609447555b224bf218ff220aae2069965939143/docs/typescript.md#slices-pattern

### CODE REVIEW

**Comment by dai-shi** [comment]
Can you run `yarn run prettier` to fix CI?

**Comment by detautama** [comment]
> Can you run `yarn run prettier` to fix CI?

Yup, nothing fixed
image

**Comment by dai-shi** [comment]
Hmm, looks like it's not working well. Let me try.

**Review by dai-shi — APPROVED** [review]
LGTM
@devanshj Can you check if it's correct, and it's aligned with the intention of the doc?

**Comment by devanshj** [comment]
I appreciate the PR but I think this is not the best way to go about it, I'll explain why.

I see you were inspired to make this PR based on the difficulty you encountered in https://github.com/pmndrs/zustand/discussions/1176. I understand the “I got stuck so I don't want someone else to get stuck” sentiment. But it's important to know whether it's “The document was missing something” or “I was missing something”.

Here the case is latter... Because in some sense the document was not targeted to you, the document is meant for people who already know what is slices pattern and how to use middlewares (ie they know already that you need to compose `devtools` with `create`)

This document only documents **additional typescript instructions** required to use zustand, it's not a document for teaching zustand or it's patterns.

I think the problem is that the readme (and some other docs too) link to the typescript document for slices pattern...

> You may wonder how to organize your code for better maintenance: [Splitting the store into separate slices](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#slices-pattern)

Instead there should be a seperate document for slices pattern (just like there used to be a wiki) or a section in readme. So the content of this PR will be more apt there.

It's important to keep this document succinct, minimal, and typescript-only because it'll be mostly read by people who have already read the readme ie the (javascript) zustand usage, so a tutorial-like prose is not apt here.

Just my two cents.

**Comment by dai-shi** [comment]
> I think the problem is that the readme (and some other docs too) link to the typescript document for slices pattern...

Yeah, I think this is weird.

Let's do that.
Would @detautama or anyone be able to work on a new doc for slice pattern? I prefer it to explain it in JS first and then TS.

**Pull request closed without merging**
