### PR TITLE
Expose `StateStorage` type and update persist midlware documentation

### PR DESCRIPTION
**Pull request by charkour**
Thanks for zustand!

I've added a details section that explains how to use custom storage engines for the `persist` middleware. The type `StateStorage` is exposed for TS users of zustand. 

Relates to discussion on issue #404 on how to use `IndexedDB` as the storage engine. 

Please let me know any changes and I would be happy to address them.

### CODE REVIEW

**Comment by charkour** [comment]
Hmm, I'm not sure why that first commit is in there. Any ideas on how to fix that?

**Review by dai-shi — COMMENTED** [review]
`<details>` is good.

**Review by AnatoleLucet — APPROVED** [review]
LGTM, thanks!

> Hmm, I'm not sure why that first commit is in there. Any ideas on how to fix that?

Not sur if it matters, but you can do an interactive rebase (something like `git rebase -i master`). In the file the git command opened: replace `pick` by `drop` on the commit that's not supposed to be there, then save & quit and force push using `git push -f` (you might verify it did what you wanted before force pushing).

**Comment by charkour** [comment]
@AnatoleLucet, thanks for the review. 

I got rid of my old commit that had no changes, but now I'm a co-author on the most recent commit. Not sure if that matters haha.

**Comment by charkour** [comment]
Oh also now the rebase things I changed `package.json`. I'm not sure why that is.

**Comment by AnatoleLucet** [comment]
If you enable ["Allow edits from maintainers"](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests), I can do the change if you want

**Comment by charkour** [comment]
@AnatoleLucet, I allowed edits from mainters. Will it work since your a Collaborator?

**Comment by AnatoleLucet** [comment]
Doesn't seem like it 😬 
Anyway, you should be able to fix it by updating your branch with something like:
```
git fetch
git rebase origin/master
git push -f
```
(as always, do a quick check before force pushing)

**Comment by charkour** [comment]
Sorry about that. It is now fixed. Thanks again for the help.

**Pull request merged**
