### PR TITLE
fix: workflow file syntax error

### PR DESCRIPTION
**Pull request by dai-shi**
there was a mistake in #1678.

### CODE REVIEW

**Comment by dai-shi** [comment]
@arjunvegda My bad, we didn't solve the `NODE_ENV` issue.

**Comment by arjunvegda** [comment]
> @arjunvegda My bad, we didn't solve the `NODE_ENV` issue.

All good! It doesn't appear to be a problem actually. [All the tests for the vitest PR are now passing](https://github.com/pmndrs/zustand/pull/1753).

**Comment by dai-shi** [comment]
@arjunvegda No, it's a syntax error: https://github.com/pmndrs/zustand/actions/runs/4855258105

**Comment by dai-shi** [comment]
@arjunvegda ended up copying for DEV/PRD.

**Comment by arjunvegda** [comment]
> @arjunvegda ended up copying for DEV/PRD.

yeah, seems like a good workaround for now!

**Review by arjunvegda — APPROVED** [review]

**Pull request merged**
