### PR TITLE
feature(persist): add method getOptions on persist api and update documentation

### PR DESCRIPTION
**Pull request by tbor00**
This pr can be relationated to:

- Expose getOptions method on persist api
- Update Documentation with examples of storage event listener
- Add test for the new method
- options were given so that this [issue](https://github.com/pmndrs/zustand/issues/714) can be solved

### CODE REVIEW

**Comment by AnatoleLucet** [comment]
Hey thanks for the PR
Unfortunately, i don't think this is a good solution to the original issue.

I think the event listener should be directly in the `persist` function/middleware and call `hydrate()` in the event handler.

**Comment by tbor00** [comment]
> Hey thanks for the PR Unfortunately, i don't think this is a good solution to the original issue.
> 
> I think the event listener should be directly in the `persist` function/middleware and call `hydrate()` in the event handler.

Hi Thanks for your comment, I don't know if I understood you correctly, do you think something like this will work?

Captura de Pantalla 2022-07-10 a la(s) 20 10 07

**Comment by AnatoleLucet** [comment]
Yes pretty much, although i'm not sure what `options.subscribe.keySubscribe` is. Maybe you meant `options.name`?
Also what's the removeEventListener used for? It feels like we're only reacting to the first storage change and omitting future ones.

**Comment by tbor00** [comment]
> Yes pretty much, although i'm not sure what `options.subscribe.keySubscribe` is. Maybe you meant `options.name`? Also what's the removeEventListener used for? It feels like we're only reacting to the first storage change and omitting future ones.

You're right, the changes are already up. I'm waiting for more comments, Thanks

**Comment by dai-shi** [comment]
`persist` middleware supports AsyncStorage in ReactNative, and possibly other non-DOM storages. So, you can't make it depend on `window`. Can you please make it an option somehow? (Note that a possible method to check `typeof window` is not recommended because some tools mock it unexpectedly.)

**Comment by tbor00** [comment]
> `persist` middleware supports AsyncStorage in ReactNative, and possibly other non-DOM storages. So, you can't make it depend on `window`. Can you please make it an option somehow? (Note that a possible method to check `typeof window` is not recommended because some tools mock it unexpectedly.)

Hmm, You're right. So I'll work on finding the best way to do this.

**Comment by tbor00** [comment]
> `persist` middleware supports AsyncStorage in ReactNative, and possibly other non-DOM storages. So, you can't make it depend on `window`. Can you please make it an option somehow? (Note that a possible method to check `typeof window` is not recommended because some tools mock it unexpectedly.)

@dai-shi Do you think adding such a function would be

Captura de Pantalla 2022-07-10 a la(s) 22 39 11
 worth it?

**Comment by dai-shi** [comment]
No, I wouldn't recommend "detecting" anything in the library code. We should just provide a capability (option/method) so that developers can use as they want.

**Comment by tbor00** [comment]
> No, no recomendaría "detectar" nada en el código de la biblioteca. Simplemente deberíamos proporcionar una capacidad (opción/método) para que los desarrolladores puedan usarla como quieran.


And a boolean in the options that if it is true execute this block? do you think it could work?

**Comment by dai-shi** [comment]
I think I'd like to avoid any DOM related code in `persist` middleware which is just useless for RN users. A separate helper function can be an option.

```js
import { persist } from 'zustand/middleware'
import { someHelperFunctionWithDOM } from 'zustand/middleware/persist'

const useFooStore = create(persist(
  ...,
  {
    someOption: someHelperFunctionWithDOM(...),
  }
))
```

Note that we could have other "subscribe" methods than DOM one. For example, one I can imagine is a storage based on firestore. The point is `persist` middleware is not only for `localStorage`/`sessionStorage`.

**Comment by tbor00** [comment]
@dai-shi  Ok, so I think something like what's in the first commit might work

**Comment by dai-shi** [comment]
Yeah, something like that. There are still many things to consider, but I think you first want to try creating a working demo?

**Comment by AnatoleLucet** [comment]
@dai-shi what about:
```ts
// impl
const withStorageDOMEvent = (store) => {
  window.addEventListener("storage", () => {
    // TODO: add .getOptions method on persist's api
    if (e.key === store.persist.getOptions().name && e.newValue) {
      store.persist.rehydrate()
    }
  })

  return // TODO: removeEventListener
}

// usage
import { withStorageDOMEvent } from "zustand/middleware"

const useMyStore = create(persist(...))

withStorageDOMEvent(useMyStore)
```

**Comment by tbor00** [comment]
> @dai-shi what about:
> 
> ```ts
> // impl
> const withStorageDOMEvent = (store) => {
>   window.addEventListener("storage", () => {
>     // TODO: add .getOptions method on persist's api
>     if (e.key === store.persist.getOptions().name && e.newValue) {
>       store.persist.rehydrate()
>     }
>   })
> 
>   return // TODO: removeEventListener
> }
> 
> // usage
> import { withStorageDOMEvent } from "zustand/middleware"
> 
> const useMyStore = create(persist(...))
> 
> withStorageDOMEvent(useMyStore)
> ```

I think what you propose sounds good too. Here I leave an [example](https://codesandbox.io/s/suscribeeventchangewithdom-example-forked-lql95t?file=/src/App.js:0-1133) of how it could be used with the changes I made

**Comment by dai-shi** [comment]
@AnatoleLucet 's idea looks good. I wasn't aware this feature should be with persist api, instead of options. (To clarify, my point was only about that `persist` middleware shouldn't have storage specific code.)

**Comment by tbor00** [comment]
@dai-shi  @AnatoleLucet  Hello, I don't know if you saw the example that I left you. If you want I can also make an example like the one you comment on.

[CODESANDBOX](https://yfxbv5.csb.app/)

**Comment by tbor00** [comment]
@AnatoleLucet @dai-shi 

I already made the last changes. It works well in both ways, which of the two do we leave? 
Also, to be honest I'm not the best with typescript. Could you give me some reference on how to type it correctly?

Example:
[codesandbox](https://2qimn3.csb.app/)

**Comment by tbor00** [comment]
Hi @AnatoleLucet , were you able to review the examples?

**Comment by AnatoleLucet** [comment]
After thinking a bit about it, i think we shouldn't include this function for the same reasons we didn't include a [`useHydration`](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#how-can-i-check-if-my-store-has-been-hydrated) hook.
As Daishi said, we don't want to lean into a specific context (web, mobile, server, etc.), so i'm thinking about only exposing the `getOptions` getter and leave the implementation to the user (with an example in the doc). After all, that's why we added the persist api :slightly_smiling_face: 

Thoughts @tbor00 @dai-shi?

**Comment by tbor00** [comment]
If it's OK, I think we can expose the getOptions and let developers make their own functions to detect changes. We could document an example of a hook for this in the documentation, what do you think? @AnatoleLucet @dai-shi

**Comment by tbor00** [comment]
ready, you can check it again? @AnatoleLucet @dai-shi

**Review by dai-shi — APPROVED** [review]
LGTM. Good work. Thanks for your contribution.

Please update PR title&description.

**Review by AnatoleLucet — CHANGES_REQUESTED** [review]

**Review by AnatoleLucet — APPROVED** [review]
Looks good, thanks for taking the time to make the changes!

**Pull request merged**
