### PR TITLE
docs: expose `enabled` devtools options in the documentation

### PR DESCRIPTION
**Pull request by FKSI**
## Summary

Document the `enabled` option for devtools middleware.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by chrisk-7777** [comment]
Looks really good @FKSI 

We're currently in the process of transitioning more and more of the readme/wiki over into the docs (https://docs.pmnd.rs/zustand/recipes/recipes#redux-devtools)

Could we capture the above in here too: https://github.com/pmndrs/zustand/blob/main/docs/recipes/recipes.mdx

**Comment by FKSI** [comment]
@chrisk-7777  didn't know about the transition (which I think provide def. a better dev experience). I made the requested change :).

**Review by chrisk-7777 — APPROVED** [review]
Winner, thanks for making that addition. 

Also 100% agree about the docs

**Comment by dai-shi** [comment]
Looks good.
Please note that we would prefer minimizing readme with moving some additional contents to docs out of readme.

**Pull request merged**
