### PR TITLE
[v5]: drop UMD/SystemJS builds

### PR DESCRIPTION
**Pull request by dbritto-dev**
## Related Issues or Discussions

Fixes #2138 

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dai-shi** [comment]
Can you follow other changes in https://github.com/pmndrs/valtio/pull/822 ?
Sorry, it wasn't very clear.


I wonder why this is passing:
https://github.com/pmndrs/zustand/actions/runs/7431727284/job/20222762466

**Comment by dbritto-dev** [comment]
@dai-shi sure, let me update it

**Comment by dbritto-dev** [comment]
@dai-shi all yours

**Review by dai-shi — APPROVED** [review]
Looks good to me! Thanks for your work!

**Pull request merged**
