### PR TITLE
[v5]: do not depend on use-sync-external-store

### PR DESCRIPTION
**Pull request by dai-shi**
for #2138

Just forgot it in https://github.com/pmndrs/zustand/pull/2237#issuecomment-1901773891

### CODE REVIEW

**Review by charkour — APPROVED** [review]
Thanks for catching this. 

We need to keep use-sync-external-store in `traditional.ts` to support the selector API, correct?

**Comment by dai-shi** [comment]
Yes, not for selector but for equalityFn.

**Comment by dai-shi** [comment]
> Warning: The result of getServerSnapshot should be cached to avoid an infinite loop

I see...

**Comment by dai-shi** [comment]
image

**Pull request merged**
