### PR TITLE
[examples] enhance responsiveness and code readability

### PR DESCRIPTION
**Pull request by stfnsr**
Regarding #203
Maybe i went a bit too far - but it looks pretty responsive to me now, and the bear is fully visible on mobile, with some inbetween states as well.
Btw, was the preformatting for the code example deactivated on purpose?

### CODE REVIEW

**Comment by dai-shi** [comment]
Preview: https://githubbox.com/stfnsr/zustand/tree/homepage-responsiveness/examples

**Comment by stfnsr** [comment]
I basically tried to optimize for maximum bear-visibility :D 
If we're running this expensive animation already, it shouldn't be covered up with a code sample ˆ_^

**Comment by stfnsr** [comment]
(Sidenote: Would it be interesting to let the interactivity influence the three-fiber scene?
Asking because being able to act across recoinciler boundaries is one of the cool things about zustand, as far as i know)

**Comment by dai-shi** [comment]
> Btw, was the preformatting for the code example deactivated on purpose?

Certainly not. Oh, so this means, the examples on master is not equal to what is deployed.
Can @drcmda confirm?

> but it looks pretty responsive to me now

Looks pretty goood.

A little improvement would be to add top margin to `counter`. width/height=1058/543

image

(The bear is not visible well with this size, but maybe fine..

**Comment by stfnsr** [comment]
Screenshot 2020-10-06 at 01 20 29
Screenshot 2020-10-06 at 01 22 47

Responsiveness and bear-visibility have been optimized further 👍

**Review by dai-shi — APPROVED** [review]
I'm OK with this. This sort of things will never be perfect.

@drcmda Are you around to check this out? (then merge and deploy?)

**Comment by dai-shi** [comment]
@stfnsr Is this counter overlap expected for you?

image

**Comment by stfnsr** [comment]
Nope, i also think this was the last one. Good catch!
Screenshot 2020-10-06 at 02 09 08

**Comment by stfnsr** [comment]
1C7A71B2-7452-4854-9620-F365B73FD34D
0FEFC58A-E8F3-445E-AA95-F4CEA85CF5DB

Landscape mode before/after

**Comment by drcmda** [comment]
nice, thanks @stfnsr @dai-shi

**Pull request merged**
