### PR TITLE
feat: blacklist and whitelist for the persist middleware

### PR DESCRIPTION
**Pull request by Qcza**
Useful option if you want to omit some fields from persisting.

### CODE REVIEW

**Comment by dai-shi** [comment]
Personally, I would avoid adding many options to persist middleware. People would eventually want to add blacklist/whitelist for nested objects.
Wouldn't serialize option work for your case?

```js
persiste({
  name: 'foo',
  serialize: (state) => {
    const stateToStringify = { ...state }
    if (blacklist) {
      blacklist.forEach((key) => delete stateToStringify[key])
    }
    return JSON.stringify(stateToStringify)
  },
})
```

Let's see how @AnatoleLucet wants as he's the original author.

**Comment by Qcza** [comment]
> Wouldn't serialize option work for your case?
> 

This is the approach I took since and it works well. But I think having the option may be more useful and clear to use for people who are familiar with the redux-persist tool.

**Review by AnatoleLucet — APPROVED** [review]
I think it's going to confuse users to modify the serializer to do a black/whitelist, but it's still an available option if (as @dai-shi said) someone wants to apply a black/whitelist on nested objects.

**Comment by dai-shi** [comment]
> clear to use for people who are familiar with the redux-persist tool.

Okay, this is convincing. I'm not very familiar with redux-persist, but if we are to only support one-level black/whitelist options, this will be good. Let's recommend customizing serialize for nested ones, as @AnatoleLucet suggested too.

I will wait for some moments and if there aren't any other comments, will merge this.

**Review by dai-shi — APPROVED** [review]
Thanks for the work and discussion!

**Comment by TkDodo** [comment]
seems like I’m a bit late to the party, but i think blocklist/allowlist would have been a better naming :/

**Comment by thgh** [comment]
Hi, came here to say the same: black/white are loaded terms and there are alternatives like include/exclude & block/allow.

**Comment by jacobbuck** [comment]
Agreed, especially given that the `master` branch has been recently renamed to `main`.

**Pull request merged**
