### PR TITLE
Remove extension warning

### PR DESCRIPTION
**Pull request by m-bp**
## Related Issues or Discussions

#2404 

## Summary

This PR removes the Redux extension warning entirely.

### CODE REVIEW

**Comment by dai-shi** [comment]
One thing we can consider is whether we should add this only in v5, assuming it's a _kind_ of breaking changes.

**Comment by dai-shi** [comment]
Would anyone like to open a PR to `v5` branch?

**Comment by charkour** [comment]
I agree that this change is likely best done as a breaking change in v5. I will make a PR.

**Comment by charkour** [comment]
https://github.com/pmndrs/zustand/pull/2466

**Comment by dai-shi** [comment]
superseded by #2466

**Pull request closed without merging**
