### PR TITLE
docs: fix testing Typescript code example

### PR DESCRIPTION
**Pull request by konclave**
## Summary

Fixed testing with Typescript code example

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
Hmm, maybe it is intentional.
Can you check #1303?

**Comment by dai-shi** [comment]
I think this is about TypeScript usage, and the TypeScript usage in docs is `create()(...)`.

**Review by dai-shi — CHANGES_REQUESTED** [review]
This is intentional for TypeScript usage `create()(...)`. The current docs is correct in that sense.
If you want to support `create(...)` usage, can you try this?

```ts
const create = <S,>(createState?: StateCreator<S>) => {
  if (!createState) return create
  const store = actualCreate<S>(createState)
  const initialState = store.getState()
  storeResetFns.add(() => store.setState(initialState, true))
  return store
}
```

**Comment by konclave** [comment]
My bad. Seems like I just messed up the option of how it could be used and imported not a default import. That was the reason of my typing issues.

**Pull request closed without merging**
