### PR TITLE
fix(build): a workaround for ESM for use-sync-external-store

### PR DESCRIPTION
**Pull request by dai-shi**
This is the same fix as https://github.com/pmndrs/valtio/pull/456, reported in https://github.com/pmndrs/valtio/issues/452.

### CODE REVIEW

**Comment by dai-shi** [comment]
Can anyone (as many as possible) try if this works on their environments?

https://ci.codesandbox.io/status/pmndrs/zustand/pr/953
See "Local Install Instructions"

**Comment by dai-shi** [comment]
It doesn't seem a right workaround: https://github.com/pmndrs/valtio/pull/469

**Comment by dai-shi** [comment]
Or, should we do it? https://github.com/pmndrs/valtio/pull/469#issuecomment-1148374528

**Comment by vemundeldegard** [comment]
@dai-shi  I tried using what was coming from the CodeSandbox, and I'm still having this issue:

 ```
  [] info  - Generating static pages (0/15)TypeError: l is not a function
    at a (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim/with-selector.production.min.js:11:204)
    at /Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim/with-selector.production.min.js:11:462
    at Object.useSyncExternalStore (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:362)
    at exports.useSyncExternalStore (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/react/cjs/react.production.min.js:25:469)
    at exports.useSyncExternalStoreWithSelector (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim/with-selector.production.min.js:11:489)
    at useStore (file:///Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/zustand/esm/index.mjs:9:17)
    at useBoundStore (file:///Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/zustand/esm/index.mjs:15:51)
    at Jc (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
    at Mc (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
    at Z (/Users/vemundeldegard/aiflow/autoflow.frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
```

**Comment by dai-shi** [comment]
Do you mean it doesn't happen without this PR? I mean `v4.0.0-rc.1`.

**Comment by vemundeldegard** [comment]
> Do you mean it doesn't happen without this PR? I mean `v4.0.0-rc.1`.

It happens also when I use this PR. This PR does not work for me. And it also happens on `v4.0.0-rc.1`.

**Comment by dai-shi** [comment]
It sounds like a different issue then. Please open a new issue with a reproduction.

**Comment by dai-shi** [comment]
Let's see how it goes.

**Pull request merged**
