### PR TITLE
Extend test case for perist middleware

### PR DESCRIPTION
**Pull request by barbogast**
This commit extends the test 'can persist state' to not only write state to the storage but to also reinitialise the store afterwards to check if the value would be rehydrated correctly.

### CODE REVIEW

**Comment by barbogast** [comment]
This feels a bit more like an integration test which simulates the whole persist-rehydrate scenario. It adds quite some setup-code, though, and maybe it should go to a new test-case.

And now that I think about it... maybe [this](https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx#L82) is proof enough. So maybe this one isn't necessary.

If you think it is I'd also add an async version. Other I'd just close this one unmerged.

**Review by AnatoleLucet — APPROVED** [review]
It might be a bit redundant, but I think it's more expressive that way.
Looks fine to me. Thanks again  for your work 🚀

**Comment by barbogast** [comment]
Oups, this one wasn't actually finished, and I forgot to flag it as such. Doesn't matter, I can do a follow up.

So far only the test for the sync storage is extended. Shall I do the same for the async version as well?

Thinking about it I realise that it might be worth it as there might be timing issues with the async version that the sync version doesn't have.

Doing this would mean that `createPersistantStore()` would either live in both `persistSync.test.jsx` and `persistAsync.test.jsx`, or it could live in a new file `tests/utils.ts` (which would be my preference).

@AnatoleLucet Your thoughts?

**Comment by AnatoleLucet** [comment]
If you have the will to write the async tests, I'd prefer if the `createPersistantStore` is shared between the sync and async tests :+1:

**Pull request merged**
