### PR TITLE
v5

### PR DESCRIPTION
**Pull request by dai-shi**
- [x] drop default exports #2238
- [x] drop deprecated features #2235
- [x] make React 18 as minimal requirement #2236
- [x] make use-sync-external-store a peer dependency #2237 #2301 #2302
- [x] make TS version requirement and tests in CI precise (follow Jotai) #2257
- [x] drop "module" condition (follow Jotai) #2270
- [x] use `"./*"` in package.json exports and change Node.js requirement #2272
- [x] drop UMD/SystemJS builds and simplify build configs #2287
- [x] drop getServerState #2300
- [x] separate react entry point #2303
- [x] drop es5 #2380 #2433
- [x] #2395
- [x] #2427
- [x] #2466
- [x] write v5 migration guide
- [x] #2580

### CODE REVIEW

**Comment by sewera** [comment]
Maybe consider changing React Snowpack to React Vite on CodeSandbox?

**Comment by dai-shi** [comment]
I think you can just add it, if you are talking about `.codesandbox/ci.json`.
Feel free to open a PR to the `main` branch.
I don't know if the container sandbox is already supported.

**Comment by sewera** [comment]
I'll see if I've got some time in the nearest future :)

**Comment by TheMikeyRoss** [comment]
I'm a noob learning things and asking around.

I noticed many libraries dropping default exports. may I ask why?

**Comment by dai-shi** [comment]
@TheMikeyRoss Can you open a new discussion? https://github.com/pmndrs/zustand/discussions/new

**Comment by charkour** [comment]
@dai-shi, I see the checklist in the PR description, could I help tackle some of the bullet points? Thanks

**Comment by dai-shi** [comment]
@charkour I was wondering when we should start this, but if you are interested please go ahead. Note that I may have some hidden requirements which isn't described well in the bullet points, so bear with me. (I think I should work on the TS one on my own.)

We do something like this https://github.com/pmndrs/valtio/pull/810, so please open PRs for each point against `v5` branch.

**Comment by charkour** [comment]
@dai-shi, are you willing to take on the next step on the task list? I can review but don't have time to code as much this week. Thanks

**Comment by dai-shi** [comment]
@dbritto-dev if you are interested you can take the next item.

**Comment by dbritto-dev** [comment]
@dai-shi let me take the next two tasks

**Comment by dai-shi** [comment]
Thanks! Please work on them one by one.

**Comment by dbritto-dev** [comment]
@dai-shi I'll take the second last too

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.0

**Comment by dai-shi** [comment]
I wonder if we should separate `zustand/react` entry point. We've done it in Jotai and Valtio.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.1

**Comment by dbritto-dev** [comment]
> I wonder if we should separate `zustand/react` entry point. We've done it in Jotai and Valtio.

We shall follow Jotai and Valtio

**Comment by dai-shi** [comment]
> > I wonder if we should separate `zustand/react` entry point. We've done it in Jotai and Valtio.
> 
> We shall follow Jotai and Valtio

#2303

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.2

Would anyone try it and see if there are any issues?

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.3

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.4

**Comment by dai-shi** [comment]
FYI @DavideSegullo We consider it a bad practice. #2395

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.5

**Comment by DavideSegullo** [comment]
> FYI @DavideSegullo We consider it a bad practice. #2395 

Oh thank you!! I tought, by reading It that It was a good pattern. Why is It a good practice?

**Comment by dai-shi** [comment]
The fact that it works now doesn't mean it works for the future version. `use-sync-external-store` is provided by React and they say they maintain it to make it work for the future. (If there was a bug, we would report it to them.) So, it's better for the community than having our own hacks.

**Comment by DavideSegullo** [comment]
> The fact that it works now doesn't mean it works for the future version. `use-sync-external-store` is provided by React and they say they maintain it to make it work for the future. (If there was a bug, we would report it to them.) So, it's better for the community than having our own hacks.

Makes sense, thank you!

**Comment by bluejoyq** [comment]
Hi. Thanks for the library, always nice. I have one minor question: why the code is remained for `createState` that  being nullable in `createStore`, which was previously left for `context`?
I checked out v5 and saw that removing it still passes all my tests, is it for external libraries?

**Comment by dbritto-dev** [comment]
> Hi. Thanks for the library, always nice. I have one minor question: why the code is remained for `createState` that  being nullable in `createStore`, which was previously left for `context`?
> 
> I checked out v5 and saw that removing it still passes all my tests, is it for external libraries?
> 
> 
> 
> ```ts
> 
> export const createStore = ((createState) =>
> 
>   createState ? createStoreImpl(createState) : createStoreImpl) as CreateStore
> 
> ```

@bluejoyq that's for middleware's

**Comment by dai-shi** [comment]
that's for typescript for middleware. it's redundant for JS. can't be helped.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-alpha.6

**Comment by dai-shi** [comment]
Zustand v5 has nothing to do with React 19, but it might be appealing if we could release it after React 19 is out. 🤔

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/5.0.0-beta.0

**Comment by dai-shi** [comment]
Oops I didn't realize we had `docs/migrations`. Anyway #2508 will restructure docs.

**Comment by charkour** [comment]
v5 works well on our v14 Next.js app (tekton.com), but it creates a warning in React Native. I'll work on making a reproduction. 

The error in React Native is: "The result of getSnapshot should be cached to avoid an infinite loop"

**Comment by dai-shi** [comment]
Published https://www.npmjs.com/package/zustand/v/5.0.0-beta.1

**Comment by dai-shi** [comment]
Published https://www.npmjs.com/package/zustand/v/5.0.0-beta.2

**Comment by dai-shi** [comment]
This is ready for quite a while. Let's merge it and ship `v5-rc`.

**Comment by dai-shi** [comment]
🎉 Kudos to @charkour who has done most of initial work.

**Comment by charkour** [comment]
Happy to help!

**Comment by dbritto-dev** [comment]
Props to @charkour :D

**Pull request merged**
