### PR TITLE
chore(deps): update example dependencies

### PR DESCRIPTION
**Pull request by tthallos**
## Related Issues or Discussions

Fixes #

## Summary
It is imported directly in the code, but it is not declared in package.json

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks. Please check CI errors.

**Comment by tthallos** [comment]
> Thanks. Please check CI errors.

ok, I'll try using yarn to test it

**Comment by dai-shi** [comment]
@tthallos a friendly reminder

**Review by devlopersabbir — APPROVED** [review]
it's fine

**Pull request merged**
