### PR TITLE
feat: deprecate default export

### PR DESCRIPTION
**Pull request by dai-shi**
close #1506

### CODE REVIEW

**Review by judicaelandria — APPROVED** [review]

**Comment by meypod** [comment]
hmm, shouldn't `zustand/vanilla` need this as well ?

**Comment by dai-shi** [comment]
Do you mean #1531? Yeah, good point.

**Comment by meypod** [comment]
I didn't mean that, It seems I was mistaken (`createStore` was actually exported and I didn't see it), but I'm actually glad if my comment could help with sth😅

**Comment by dai-shi** [comment]
😄

**Pull request merged**
