### PR TITLE
improve middleware/combine types

### LINKED ISSUE #216: Enable NamedSet when using devtools and combine
When using devtools with combine, combine's `set` is not of type `NamedSet` so typescript does not permit to give a third parameter to `set` function. Is there a way to work around it?

image

maybe exporting interface from `middleware.ts:31`, I can force it to use.

### PR DESCRIPTION
**Pull request by dai-shi**
close #216 

It uses CustomSetState.
(Note, if we'd support #212, it'd require total overhaul.)

### CODE REVIEW

**Comment by dai-shi** [comment]
@rosostolato Would you try if this works for both with devtools and without devtools?

**Comment by rosostolato** [comment]
It's working fine! I also created a PR with tests for devtools and combine https://github.com/pmndrs/zustand/pull/230

**Comment by dai-shi** [comment]
Good news. Thanks. Let me merge this.

**Comment by dai-shi** [comment]
This doesn't seem to be a right fix. Reverted: 9b4aadb

**Pull request merged**
